import { defineConfig } from 'astro/config';
import { existsSync, readFileSync } from 'fs';
import starlight from '@astrojs/starlight';
import starlightLinksValidator from 'starlight-links-validator';
import starlightLlmsTxt from 'starlight-llms-txt';
import starlightSidebarTopics from 'starlight-sidebar-topics';
import { PRODUCTS, versionSlug, versionedContentDir, versionedLink } from './src/products.ts';

import tailwindcss from '@tailwindcss/vite';
import { LikeC4VitePlugin } from 'likec4/vite-plugin';
import starlightImageZoom from 'starlight-image-zoom';
import react from '@astrojs/react';
import starlightGitHubAlerts from 'starlight-github-alerts';

// Read per-product versions from .versions JSON (written by scripts/discover-versions.mjs).
// Format: { "owner/repo": { "repo": "...", "branch": "...", "versions": [...], "latestTag": "..." } }
let versionsFile = {};
try {
  versionsFile = JSON.parse(readFileSync('.versions', 'utf8'));
} catch { /* not present in local dev — no archived versions built */ }

// Index .versions by repo for O(1) lookups, then re-key by product id.
const versionsByRepo = Object.fromEntries(Object.values(versionsFile).map(v => [v.repo, v]));
const productVersions = Object.fromEntries(
  PRODUCTS.map(p => {
    const allVersions = versionsByRepo[p.repo]?.versions ?? [];
    const available = allVersions.filter(ver =>
      existsSync(`./src/content/docs/${versionedContentDir(p, ver)}`)
    );
    return [p.id, available];
  })
);
const productLatestTags = Object.fromEntries(
  PRODUCTS.flatMap(p => {
    const tag = versionsByRepo[p.repo]?.latestTag;
    return tag ? [[p.id, tag]] : [];
  })
);

function titleCase(name) {
  return name.replace(/-/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
}

function makeSidebarItems(prefix, sidebarOrder) {
  if (!sidebarOrder || sidebarOrder.length === 0) return [];
  return sidebarOrder
    .map(e => typeof e === 'string' ? { dir: e, label: titleCase(e) } : e)
    .filter(({ dir }) => !prefix || existsSync(`./src/content/docs/${prefix}/${dir}`))
    .map(({ label, dir }) => ({
      label,
      autogenerate: { directory: prefix ? `${prefix}/${dir}` : dir },
      collapsed: true,
    }));
}

/** Load a version-specific config from .product-configs/{repoName}.{verSlug}.json */
function loadVersionSidebarOrder(repo, verSlug) {
  const repoName = repo.split('/').pop();
  const path = `.product-configs/${repoName}.${verSlug}.json`;
  if (!existsSync(path)) return null;
  try {
    return JSON.parse(readFileSync(path, 'utf8')).sidebarOrder ?? null;
  } catch (err) {
    console.warn(`Warning: failed to parse version config at ${path}: ${err.message}`);
    return null;
  }
}

// One sidebar topic per product (config loaded from .product-configs/).
const productTopics = PRODUCTS.map((product) => ({
  id: product.id,
  label: product.label,
  link: product.link,
  items: makeSidebarItems(product.contentDir, product.sidebarOrder),
}));

// One sidebar topic per archived version of each product.
const versionedTopics = PRODUCTS.flatMap(product => {
  const versions = productVersions[product.id] ?? [];
  return versions.map(ver => {
    const verSlug = versionSlug(ver);
    const verSidebarOrder = loadVersionSidebarOrder(product.repo, verSlug) ?? product.sidebarOrder;
    return {
      id: `${product.id}-${verSlug}`,
      label: product.label,
      link: versionedLink(product, ver),
      items: makeSidebarItems(versionedContentDir(product, ver), verSidebarOrder),
    };
  });
});

// Unlisted-page topic associations: pages that exist but aren't in any autogenerated
// sidebar section (product root/index pages, 404 pages, versioned 404 pages).
// Computed automatically from products — no manual unlistedPaths needed.
const topicsOption = Object.fromEntries([
  ...PRODUCTS.map((p, i) => [
    p.id,
    [`/${p.contentDir}`, `/${p.contentDir}/404`, ...(i === 0 ? ['/404'] : [])],
  ]),
  ...PRODUCTS.flatMap(product => {
    const versions = productVersions[product.id] ?? [];
    return versions.map(ver => {
      const contentDir = versionedContentDir(product, ver);
      return [`${product.id}-${versionSlug(ver)}`, [`/${contentDir}/404`, `/${contentDir}`]];
    });
  }),
]);

// https://astro.build/config
export default defineConfig({
  site: 'https://uds.defenseunicorns.com/docs/',
  prefetch: true,
  redirects:
  {
    '/docs': '/',
    '/en': '/',
  },

  integrations: [
    react(),
    starlight({
      pagination: false,
      routeMiddleware: './src/routeData.ts',
      plugins: [
        starlightGitHubAlerts(),
        starlightLinksValidator({
          exclude: ({ slug }) => /(?:^|\/)404$/.test(slug) || /(?:^|\/)v\d+-\d+\//.test(slug),
        }),
        starlightImageZoom(),
        starlightLlmsTxt({
          projectName: 'UDS Documentation',
          description: 'Authoritative docs for UDS.',
          details: [
            '- CLI examples use `uds` and bash-like shells.',
            '- Start with Getting Started; use CLI Reference for flags.',
          ].join('\n'),
          optionalLinks: [
            ...PRODUCTS.map(p => ({ label: `${p.label} (GitHub)`, url: `https://github.com/${p.repo}` })),
            { label: 'Zarf Docs', url: 'https://docs.zarf.dev/' },
          ],
          // TODO: customSets and promote use static content paths — update these
          // when adding new products or changing a product's contentDir.
          customSets: [
            { label: 'Getting Started', paths: ['core/getting-started/**'], description: 'Install and first steps.' },
            { label: 'Concepts', paths: ['core/concepts/**'], description: 'How UDS Core works and its major features.' },
            { label: 'Operations & Maintenance', paths: ['core/operations/**'], description: 'Day-2 operations, upgrades, and runbooks.' },
            { label: 'CLI', paths: ['cli/**'], description: 'UDS CLI reference and usage.' },
          ],
          promote: ['index*', 'core/getting-started/**', 'core/overview/**', 'core/concepts/**', 'core/reference/cli/**', 'core/operations/**', 'cli/**'],
          minify: { note: true, tip: true, caution: true, danger: true, details: true, whitespace: true },
          pageSeparator: '\n\n-----\n\n',
          rawContent: true,
        }),
        starlightSidebarTopics([
          ...productTopics,
          ...versionedTopics,
        ], { topics: topicsOption }),
      ],
      defaultLocale: 'root',
      locales: {
        root: {
          label: 'English',
          lang: 'en',
        }
      },
      // The title is set to '' because otherwise it shows in the top navigation which is redundant with the logo.
      // However, if this is done, the title delimiter has no text after it, which affects what you see in the
      // page title (e.g. Basic Requirements | [title]). We can fix this by changing the delimiter value and
      // ensure the logo has alternative text for accessibility purposes.
      title: '',
      titleDelimiter: '| UDS',
      lastUpdated: true,
      customCss: [
        './src/tailwind.css',
      ],
      logo: {
        light: './src/assets/UDS_Logo_Dark.svg',
        dark: './src/assets/UDS_Logo_White.svg',
        alt: 'Unicorn Delivery Service'
      },
      components: {
        Banner: './src/components/Banner.astro',
        Footer: './src/components/Footer.astro',
        Head: './src/components/Head.astro',
        Header: './src/components/Header.astro',
        MarkdownContent: './src/components/MarkdownContent.astro',
        ThemeProvider: './src/components/ThemeProvider.astro',
        Sidebar: './src/components/Sidebar.astro',
        Search: './src/components/Search.astro'
      },
      social: [
        {
          icon: 'github',
          href: 'https://github.com/defenseunicorns',
          label: 'GitHub'
        }
      ],
    },
    )],
  vite: {
    resolve: { preserveSymlinks: true },
    define: {
      // Per-product archived versions for VersionPicker & Search
      __PRODUCT_VERSIONS__: JSON.stringify(productVersions),
      // Per-product latest release tags for VersionPicker label
      __PRODUCT_LATEST_TAGS__: JSON.stringify(productLatestTags),
      // Product registry for client-side components (VersionPicker, Search)
      __PRODUCTS__: JSON.stringify(PRODUCTS.map(({ id, label, link, repo }) => ({ id, label, link, githubRepo: repo ?? null }))),
    },
    plugins: [
      tailwindcss(),
      LikeC4VitePlugin({
        modelRoot: './src/content/docs/.c4/',
      }),
    ],
  },
});
