import { defineConfig } from 'astro/config';
import { existsSync, readFileSync } from 'fs';
import starlight from '@astrojs/starlight';
import starlightLinksValidator from 'starlight-links-validator';
import starlightLlmsTxt from 'starlight-llms-txt';
import starlightSidebarTopics from 'starlight-sidebar-topics';
import { PRODUCTS, DEFAULT_SIDEBAR_SECTIONS, versionSlug, versionedContentDir, versionedLink } from './src/products.ts';

import tailwindcss from '@tailwindcss/vite';
import { LikeC4VitePlugin } from 'likec4/vite-plugin';
import starlightImageZoom from 'starlight-image-zoom';
import react from '@astrojs/react';
import starlightGitHubAlerts from 'starlight-github-alerts'

// Read per-product versions from .versions JSON (written by scripts/discover-versions.mjs).
// Format: { "core": { "versions": [...], "latestTag": "v0.63.0", "contentDir": "...", "sources": [...], ... } }
let versionsFile = {};
try {
  versionsFile = JSON.parse(readFileSync('.versions', 'utf8'));
} catch { /* not present in local dev — no archived versions built */ }
// Extract just the version lists keyed by product id (for Vite define + topic generation)
const productVersions = Object.fromEntries(
  Object.entries(versionsFile).map(([id, data]) => [id, data.versions ?? []])
);
const productLatestTags = Object.fromEntries(
  Object.entries(versionsFile).flatMap(([id, data]) => data.latestTag ? [[id, data.latestTag]] : [])
);

function makeSidebarItems(prefix = '', sections = DEFAULT_SIDEBAR_SECTIONS) {
  return sections
    .filter(({ dir }) => !prefix || existsSync(`./src/content/docs/${prefix}/${dir}`))
    .map(({ label, dir }) => ({
      label,
      autogenerate: { directory: prefix ? `${prefix}/${dir}` : dir },
      collapsed: true,
    }));
}

// One sidebar topic per product (from products.ts — add new products there).
const productTopics = PRODUCTS.map((product) => ({
  id: product.id,
  label: product.label,
  link: product.link,
  items: makeSidebarItems(product.contentDir, product.sidebarSections),
}));

// One sidebar topic per archived version of each product.
const versionedTopics = PRODUCTS.flatMap(product => {
  const versions = productVersions[product.id] ?? [];
  return versions.map(ver => ({
    id: `${product.id}-${versionSlug(ver)}`,
    label: `${product.label} ${ver.replace(/\.\d+$/, '')}`,
    link: versionedLink(product, ver),
    items: makeSidebarItems(versionedContentDir(product, ver), product.sidebarSections),
  }));
});

// Unlisted-page topic associations: pages that exist but aren't in any autogenerated
// sidebar section (product root/index pages, 404 pages, versioned 404 pages).
const topicsOption = Object.fromEntries([
  ...PRODUCTS.flatMap(p => p.unlistedPaths?.length ? [[p.id, p.unlistedPaths]] : []),
  ...PRODUCTS.flatMap(product => {
    const versions = productVersions[product.id] ?? [];
    return versions.map(ver => {
      const contentDir = versionedContentDir(product, ver);
      return [`${product.id}-${versionSlug(ver)}`, [`/${contentDir}/404`]];
    });
  }),
]);

// https://astro.build/config
export default defineConfig({
  site: 'https://uds.defenseunicorns.com/docs/',

  redirects:
  {
    '/docs': '/',
    '/en': '/',
  },

  integrations: [
    react(),
    starlight({
      plugins: [
        starlightGitHubAlerts(),
        starlightLinksValidator({
          exclude: ({ slug }) => slug === '404' || /(?:^|\/)v\d+-\d+\//.test(slug),
        }),
        starlightImageZoom(),
        starlightLlmsTxt({
          projectName: 'UDS Documentation',
          description: 'Authoritative docs for Unicorn Delivery Service (UDS).',
          details: [
            '- CLI examples use `uds` and bash-like shells.',
            '- Start with Getting Started; use CLI Reference for flags.',
          ].join('\n'),
          optionalLinks: [
            { label: 'UDS Core (GitHub)', url: 'https://github.com/defenseunicorns/uds-core' },
            { label: 'UDS CLI (GitHub)', url: 'https://github.com/defenseunicorns/uds-cli' },
            { label: 'Zarf Docs', url: 'https://docs.zarf.dev/' },
          ],
          customSets: [
            { label: 'Getting Started', paths: ['getting-started/**'], description: 'Install and first steps.' },
            { label: 'Concepts', paths: ['concepts/**'], description: 'How UDS Core works and its major features.' },
            { label: 'Operations & Maintenance', paths: ['operations/**'], description: 'Day-2 operations, upgrades, and runbooks.' },
          ],
          promote: ['index*', 'getting-started/**', 'overview/**', 'concepts/**', 'reference/cli/**', 'operations/**'],
          minify: { note: true, tip: true, caution: true, danger: true, details: true, whitespace: true },
          pageSeparator: '\n\n-----\n\n',
          rawContent: true,
        }),
        starlightSidebarTopics([
          ...productTopics,
          ...versionedTopics,
        ], { topics: topicsOption }),
      ],
      routeMiddleware: './src/routeData.ts',
      defaultLocale: 'root',
      locales: {
        root: {
          label: 'English',
          lang: 'en',
        }
      },
      // The title is set to '' because otherwise it shows in the top navigation which is redundant with the logo.
      // However, if this is done, the title delimiter has no text after it, which affects what you see in the
      // page title (e.g. Basic Requirements | [title]). We can fix this by changing the delimiter value and
      // ensure the logo has alternative text for accessibility purposes.
      title: '',
      titleDelimiter: '| UDS',
      lastUpdated: true,
      customCss: [
        './src/tailwind.css',
      ],
      logo: {
        light: './src/assets/UDS_Logo_Dark.svg',
        dark: './src/assets/UDS_Logo_White.svg',
        alt: 'Unicorn Delivery Service'
      },
      components: {
        Footer: './src/components/Footer.astro',
        Head: './src/components/Head.astro',
        Header: './src/components/Header.astro',
        MarkdownContent: './src/components/MarkdownContent.astro',
        ThemeProvider: './src/components/ThemeProvider.astro',
        Sidebar: './src/components/Sidebar.astro',
        Search: './src/components/Search.astro'
      },
      social: [
        {
          icon: 'github',
          href: 'https://github.com/defenseunicorns/uds-core',
          label: 'GitHub'
        }
      ],
    },
    )],
  vite: {
    resolve: { preserveSymlinks: true },
    define: {
      // Per-product archived versions for VersionPicker & Search
      __PRODUCT_VERSIONS__: JSON.stringify(productVersions),
      // Per-product latest release tags for VersionPicker label
      __PRODUCT_LATEST_TAGS__: JSON.stringify(productLatestTags),
      // Product registry for client-side components (VersionPicker, Search)
      __PRODUCTS__: JSON.stringify(PRODUCTS.map(({ id, label, link, source }) => ({ id, label, link, githubRepo: source?.repo ?? null }))),
    },
    plugins: [
      tailwindcss(),
      LikeC4VitePlugin({
        modelRoot: './src/content/docs/.c4/',
      }),
    ],
  },
});
