/**
 * Product configuration — resolved from upstream docs.config.json files.
 *
 * To add a new product:
 *   1. Add an entry to src/products.json (repo, optional branch).
 *   2. Ensure the upstream repo has a docs/docs.config.json defining id, label, contentDir, description, sidebarOrder.
 *   3. Run `npm run build` to verify everything wires up.
 *
 * See CONTRIBUTING.md → "Adding a New Product" for the full walkthrough.
 */

import { existsSync, readdirSync, readFileSync } from 'fs';

/** Filename of the directory rename map generated by integration.ts. */
export const DIR_RENAMES_FILENAME = 'dir-renames.json';

/** Resolved product config — merged from products.json + upstream docs.config.json */
export interface ProductConfig {
  id: string;
  label: string;
  link: string;
  contentDir: string;
  repo: string;
  description?: string;
  sidebarOrder: (string | { dir: string; label: string })[];
}

/**
 * Convert a semver tag to a URL-safe slug (drop patch, dots → hyphens).
 * Hyphens are required because Astro strips dots from content collection slugs.
 * e.g. v0.61.0 → v0-61, v1.2.0 → v1-2
 */
export function versionSlug(ver: string): string {
  return ver.replace(/\.\d+$/, '').replace(/\./g, '-');
}

/**
 * Build the versioned content directory path for a product + version.
 * e.g. contentDir 'my-product' + ver 'v0.61.0' → 'my-product/v0-61'
 */
export function versionedContentDir(product: ProductConfig, ver: string): string {
  const slug = versionSlug(ver);
  return product.contentDir ? `${product.contentDir}/${slug}` : slug;
}

/**
 * Build the versioned URL prefix for a product + version.
 * e.g. contentDir 'my-product' + ver 'v0.61.0' → '/my-product/v0-61/'
 */
export function versionedLink(product: ProductConfig, ver: string): string {
  const slug = versionSlug(ver);
  return product.contentDir ? `/${product.contentDir}/${slug}/` : `/${slug}/`;
}

/**
 * Load resolved product configs from .product-configs/ directory.
 * The integration script writes these after cloning upstream repos and
 * reading their docs/docs.config.json files.
 *
 * Falls back to an empty array when .product-configs/ does not exist
 * (e.g. local dev without running the integration script).
 */
export function loadProductConfigs(): ProductConfig[] {
  const configDir = '.product-configs';
  if (!existsSync(configDir)) return [];

  // Read src/products.json to get the authoritative product order.
  // readdirSync order is filesystem-dependent and not reliable for determining
  // which product is "primary" (PRODUCTS[0]).
  let repoOrder: Map<string, number> = new Map();
  try {
    const productsJson: Array<{ repo: string }> = JSON.parse(
      readFileSync('src/products.json', 'utf8')
    );
    repoOrder = new Map(productsJson.map((p, i) => [p.repo, i]));
  } catch {
    // Fall back to filesystem order if products.json can't be read.
  }

  return readdirSync(configDir)
    .filter(f => f.endsWith('.json') && !/\.v\d+-\d+\.json$/.test(f) && f !== DIR_RENAMES_FILENAME)
    .map(f => {
      const path = `${configDir}/${f}`;
      try {
        const data = JSON.parse(readFileSync(path, 'utf8'));
        for (const field of ['id', 'label', 'contentDir'] as const) {
          if (!data[field]) throw new Error(`missing required field '${field}'`);
        }
        return {
          id: data.id,
          label: data.label,
          link: `/${data.contentDir}/`,
          contentDir: data.contentDir,
          repo: data.repo,
          description: data.description,
          sidebarOrder: data.sidebarOrder ?? [],
        };
      } catch (err) {
        throw new Error(`Failed to parse product config ${path}: ${(err as Error).message}`);
      }
    })
    .sort((a, b) => (repoOrder.get(a.repo) ?? Infinity) - (repoOrder.get(b.repo) ?? Infinity));
}

export const PRODUCTS: ProductConfig[] = loadProductConfigs();
