/**
 * Product configuration — the single place to register products on this docs site.
 *
 * To add a new product:
 *   1. Add an entry to src/products.json (source, versioning, sidebar sections, etc.).
 *   2. Create src/content/docs/{contentDir}/index.md as the product root page.
 *   3. Run `npm run build` to verify everything wires up.
 *
 * See CONTRIBUTING.md → "Adding a New Product" for the full walkthrough.
 */

import productsData from './products.json';

export interface ContentSource {
  /** GitHub repo in "owner/name" format */
  repo: string;
  /** Branch to clone (default: 'main') */
  branch?: string;
  /** Path to docs within the repo (default: 'docs') */
  docsPath?: string;
  /**
   * 'base' clones with --delete (clean slate); 'overlay' merges on top.
   * Exactly one product should use 'base' — typically Core.
   * Default: 'overlay'
   */
  mode?: 'base' | 'overlay';
}

export interface VersioningConfig {
  /** GitHub repo in "owner/name" format for version discovery (defaults to source.repo if omitted) */
  repo?: string;
  /** Path to docs within the repo (defaults to source.docsPath, then 'docs') */
  docsPath?: string;
  /** Number of archived versions to keep, not including latest (default: 5) */
  archiveCount?: number;
}

export interface SidebarSection {
  label: string;
  dir: string;
}

/** Default sidebar sections shared by most products. */
export const DEFAULT_SIDEBAR_SECTIONS: SidebarSection[] = [
  { label: 'Overview',                 dir: 'overview' },
  { label: 'Getting Started',          dir: 'getting-started' },
  { label: 'Concepts',                 dir: 'concepts' },
  { label: 'How-to Guides',            dir: 'how-to-guides' },
  { label: 'Reference',               dir: 'reference' },
  { label: 'Operations & Maintenance', dir: 'operations' },
];

export interface ProductConfig {
  /**
   * Unique id — must match the starlightSidebarTopics topic id.
   * Avoid hyphens: the id is used for env var overrides (VERSIONS_{id})
   * and hyphens are invalid in shell variable names.
   */
  id: string;
  /** Display label shown in the product dropdown */
  label: string;
  /** Root URL for this product (e.g. '/' for Core, '/my-product/' for My Product) */
  link: string;
  /**
   * Directory under src/content/docs/ that holds this product's content.
   * Use '' (empty string) for the root (UDS Core).
   */
  contentDir: string;
  /**
   * Page slugs (with leading slash) that belong to this product but aren't
   * covered by any autogenerated sidebar section — typically root/index pages
   * and 404 pages. Required so starlightSidebarTopics can associate them.
   */
  unlistedPaths?: string[];
  /** Where this product's latest docs come from. Omit for products with only local content. */
  source?: ContentSource;
  /** Optional versioning — when set, archived versions are built for this product. */
  versioning?: VersioningConfig;
  /**
   * Sidebar sections for this product. Defaults to DEFAULT_SIDEBAR_SECTIONS.
   * Override this to use different section labels/dirs for a specific product.
   */
  sidebarSections?: SidebarSection[];
}

/**
 * Convert a semver tag to a URL-safe slug (drop patch, dots → hyphens).
 * Hyphens are required because Astro strips dots from content collection slugs.
 * e.g. v0.61.0 → v0-61, v1.2.0 → v1-2
 */
export function versionSlug(ver: string): string {
  return ver.replace(/\.\d+$/, '').replace(/\./g, '-');
}

/**
 * Build the versioned content directory path for a product + version.
 * Core (contentDir ''): 'v0-61'
 * My Product (contentDir 'my-product'): 'my-product/v1-2'
 */
export function versionedContentDir(product: ProductConfig, ver: string): string {
  const slug = versionSlug(ver);
  return product.contentDir ? `${product.contentDir}/${slug}` : slug;
}

/**
 * Build the versioned URL prefix for a product + version.
 * Core (link '/'): '/v0-61/'
 * My Product (link '/my-product/'): '/my-product/v1-2/'
 */
export function versionedLink(product: ProductConfig, ver: string): string {
  const slug = versionSlug(ver);
  return product.contentDir ? `/${product.contentDir}/${slug}/` : `/${slug}/`;
}

export const PRODUCTS: ProductConfig[] = productsData as unknown as ProductConfig[];
