// src/routeData.ts
import { defineRouteMiddleware } from '@astrojs/starlight/route-data';
import type { StarlightRouteData } from '@astrojs/starlight/route-data';

// Convert a slug-like directory name to a readable label by replacing hyphens
// with spaces and capitalizing each word. Only transforms all-lowercase slugs —
// labels with spaces or uppercase were set explicitly and are left unchanged.
// e.g. "single-sign-on" → "Single Sign On"
function labelFromSlug(label: string): string {
  if (!/^[a-z][a-z0-9-]*$/.test(label)) return label;
  return label.split('-').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ');
}

function transformSidebarLabels(entries: StarlightRouteData['sidebar']): void {
  for (const entry of entries) {
    if (entry.type === 'group') {
      entry.label = labelFromSlug(entry.label);
      transformSidebarLabels(entry.entries);
    }
  }
}

function productFromRouteId(id: string): string {
  // id is like: "registry/...", "fleet/...", or "getting-started/..." etc.
  const first = id.split('/')[0];

  if (first === 'registry') return 'Registry';
  if (first === 'fleet') return 'Fleet';
  return 'UDS Core';
}

export const onRequest = defineRouteMiddleware((context) => {
  const route = context.locals.starlightRoute;

  // Defensive: route/head should exist on normal Starlight pages
  if (!route?.head || !route?.id) return;

  const product = productFromRouteId(route.id);

  // Pagefind supports inline metadata "key:value" and it can live in <head>.
  route.head.push({
    tag: 'meta',
    attrs: {
      'data-pagefind-meta': `product:${product}`,
    },
  });

  // Transform autogenerated sidebar group labels from slug format (e.g. "single-sign-on")
  // to readable title case (e.g. "Single Sign On"). Only slug-like labels are affected —
  // explicitly set labels (e.g. "Getting Started", "How-to Guides") are left unchanged.
  if (route.sidebar) {
    transformSidebarLabels(route.sidebar);
  }
});
